org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=equalbreak
mod_name=Equal Break
mod_version=1.0.0
mod_group_id=com.example.equalbreak
mod_authors=You

neoforge_version=21.1.172
neoforge_version_range=[21.1,)
minecraft_version_range=[1.21.1,1.22)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
