modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Adds a server command that toggles Fortifications mode.
While active, every block breaks at the same speed as deepslate.
Unbreakable and instant-break blocks are unaffected.
'''
authors="${mod_authors}"

[[mixins]]
config="fortifications.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="architectury"
    type="required"
    versionRange="[13.0.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ftblibrary"
    type="required"
    versionRange="[2101.1.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ftbteams"
    type="required"
    versionRange="[2101.1.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="default_skill_trees"
    type="optional"
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"
